# Generated by Django 5.0.4 on 2024-04-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('full_name', models.CharField(blank=True, max_length=30, null=True)),
                ('repair_category', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
